// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeHyO3TAWMXimNn7FXJEFGNmquUD6Rbqo',
    appId: '1:632518514749:android:5523ef3a336b5f04fd3254',
    messagingSenderId: '632518514749',
    projectId: 'wellbeing-459d7',
    storageBucket: 'wellbeing-459d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1IcDri5QmXMQtJBPfm9LXUYlSz1Rj_lw',
    appId: '1:632518514749:ios:99f7b4b664b2c33afd3254',
    messagingSenderId: '632518514749',
    projectId: 'wellbeing-459d7',
    storageBucket: 'wellbeing-459d7.firebasestorage.app',
    iosClientId: '632518514749-aso19vf2f27p71atqahkqq87rlss23g9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
